(function() {var implementors = {};
implementors["lcms2"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/borrow/trait.Borrow.html\" title=\"trait core::borrow::Borrow\">Borrow</a>&lt;<a class=\"struct\" href=\"lcms2/struct.MLURef.html\" title=\"struct lcms2::MLURef\">MLURef</a>&gt; for <a class=\"struct\" href=\"lcms2/struct.MLU.html\" title=\"struct lcms2::MLU\">MLU</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/borrow/trait.Borrow.html\" title=\"trait core::borrow::Borrow\">Borrow</a>&lt;<a class=\"struct\" href=\"lcms2/struct.NamedColorListRef.html\" title=\"struct lcms2::NamedColorListRef\">NamedColorListRef</a>&gt; for <a class=\"struct\" href=\"lcms2/struct.NamedColorList.html\" title=\"struct lcms2::NamedColorList\">NamedColorList</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/borrow/trait.Borrow.html\" title=\"trait core::borrow::Borrow\">Borrow</a>&lt;<a class=\"struct\" href=\"lcms2/struct.PipelineRef.html\" title=\"struct lcms2::PipelineRef\">PipelineRef</a>&gt; for <a class=\"struct\" href=\"lcms2/struct.Pipeline.html\" title=\"struct lcms2::Pipeline\">Pipeline</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/borrow/trait.Borrow.html\" title=\"trait core::borrow::Borrow\">Borrow</a>&lt;<a class=\"struct\" href=\"lcms2/struct.StageRef.html\" title=\"struct lcms2::StageRef\">StageRef</a>&gt; for <a class=\"struct\" href=\"lcms2/struct.Stage.html\" title=\"struct lcms2::Stage\">Stage</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/borrow/trait.Borrow.html\" title=\"trait core::borrow::Borrow\">Borrow</a>&lt;<a class=\"struct\" href=\"lcms2/struct.ToneCurveRef.html\" title=\"struct lcms2::ToneCurveRef\">ToneCurveRef</a>&gt; for <a class=\"struct\" href=\"lcms2/struct.ToneCurve.html\" title=\"struct lcms2::ToneCurve\">ToneCurve</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
